wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      4: 3.7.7
      5: 0.10.24
      8:
      - 1
      - 3
      - 5
learning_rate:
  desc: null
  value: 1.0e-05
